# Generated by Django 5.1.5 on 2025-03-11 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_gallery', models.ImageField(blank=True, null=True, upload_to='crop_images/')),
                ('crop_name', models.CharField(max_length=255)),
                ('short_desc', models.TextField()),
                ('batch_number', models.CharField(max_length=100)),
                ('batch_quantity', models.PositiveIntegerField()),
                ('harvest_date', models.DateField()),
                ('storage_date', models.DateField()),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
