# Generated by Django 5.1.5 on 2025-03-11 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_crop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('short_desc', models.TextField()),
                ('weight', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dimension', models.CharField(max_length=255)),
                ('batch_number', models.CharField(max_length=100)),
                ('crop_batch_number', models.CharField(max_length=100)),
                ('batch_quantity', models.PositiveIntegerField()),
                ('storage_date', models.DateField()),
                ('packaging_date', models.DateField()),
                ('farmer_name', models.CharField(max_length=255)),
                ('farmer_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='accounts.product')),
            ],
        ),
    ]
